### ISSUE TITLE
java -jar jython-standalone-2.7.2.jar -m pip install requests is not working 

### ISSUE THREAD

**Issue by RAVIPRAJ** [0xd114/CopyAsPyRequest#1]
java -jar jython-standalone-2.7.2.jar -m pip install re
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.io.StreamIO (file:/home/ravindra/Downloads/jython-standalone-2.7.2.jar) to field java.io.FilterOutputStream.out
WARNING: Please consider reporting this to the maintainers of org.python.core.io.StreamIO
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
DEPRECATION: A future version of pip will drop support for Python 2.7.
Collecting re
  ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for requests

**Comment by cperkkk** [comment]
why are you installing re ? it should be `requests` package
